version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    environment:
      ENV_NAME: STAGE
    steps:
      - run: echo "Building building building!"
      - run: sh ./scripts/declare-variables.sh
      - run: echo $LEXICALA_USERNAME
