version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    environment:
      ENV_NAME: STAGE
    steps:
      - checkout
      - run: bash ./scripts/install-build-depdendencies.sh
      - run: terraform --version
      - run: bash ./scripts/declare-variables.sh
      - run: bash ./scripts/run-terraform.sh
