version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    environment:
      LEXICALA_USERNAME: ${STAGE_LEXICALA_USERNAME}
    steps:
      - run: echo "Building building building!"
      - run: echo $STAGE_LEXICALA_USERNAME
      - run: echo $LEXICALA_USERNAME
