version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    environment:
      ENV_NAME: STAGE
    steps:
      - run: echo "Building building building!"
      - run:
          name: Steup variables
          command: |
            echo "Environment ${ENV_NAME}"
            LEXICALA_USERNAME_VAR="${ENV_NAME}_LEXICALA_USERNAME"
            LEXICALA_USERNAME="${!LEXICALA_USERNAME_VAR}"
            echo $LEXICALA_USERNAME
