version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    environment:
      ENV_NAME: STAGE
    steps:
      #      - checkout
      - run: sudo apt-get install -y unzip
      - run: wget https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
      - run: unzip terraform_1.1.2_linux_amd64.zip
      - run: sudo mv terraform /usr/local/bin/
      - run: terraform --version
      - run: bash ./scripts/declare-variables.sh
      - run: terraform -version
