version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
      - image: circleci/node:14
    working_directory: ~/repo
    environment:
      ENV_NAME: STAGE
    steps:
      - checkout
      - run: bash ./scripts/declare-variables.sh
      - run: terraform -version
