version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    environment:
      ENV_NAME: STAGE
    steps:
      #      - checkout
      - run: sudo apt-get install -y unzip
      - run: bash ./scripts/declare-variables.sh
      - run: terraform -version
