name: Deploy Infrastructure

on:
  push:

jobs:
  deploy:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

#      - uses: borales/actions-yarn@v2.3.0
#        with:
#          cmd: install

      - uses: docker://hashicorp/terraform:latest
        with:
          cmd: terraform init
